# Simulation Configuration
# This file contains tunable parameters for the simulation

# General simulation parameters
simulation:
  name: "default_simulation"
  description: "Base simulation configuration"
  version: "1.0.0"
  max_duration_seconds: 3600  # Maximum duration in seconds (1 hour)
  time_step: 0.1  # Simulation time step in seconds
  real_time_factor: 1.0  # Target real-time factor (1.0 = real-time)
  random_seed: 42  # Random seed for reproducibility

# Physics parameters
physics:
  gravity: 9.81  # m/s²
  air_density: 1.225  # kg/m³
  water_density: 1025.0  # kg/m³
  wind:
    speed: 5.0  # m/s
    direction: 0.0  # degrees (0 = North, 90 = East)
    gustiness: 0.2  # 0-1, randomness in wind

# Vessel parameters
vessel:
  mass: 1000.0  # kg
  length: 10.0  # meters
  width: 3.0  # meters
  height: 2.0  # meters
  drag_coefficient: 0.82
  max_speed: 10.0  # m/s
  max_acceleration: 2.0  # m/s²
  
  # Thrust parameters
  thrust:
    max_forward: 5000.0  # Newtons
    max_reverse: 2000.0  # Newtons
    response_time: 1.0  # seconds

# Sensor parameters
sensors:
  gps:
    update_rate: 1.0  # Hz
    position_error: 1.0  # meters
    velocity_error: 0.1  # m/s
    
  imu:
    update_rate: 100.0  # Hz
    acceleration_error: 0.1  # m/s²
    gyro_error: 0.01  # rad/s
    
  depth_sensor:
    update_rate: 10.0  # Hz
    error: 0.05  # meters

# Environmental parameters
environment:
  current:
    speed: 0.5  # m/s
    direction: 45.0  # degrees
    depth_variation: 0.2  # m
    
  waves:
    enable: true
    height: 0.5  # meters
    period: 5.0  # seconds
    direction: 0.0  # degrees
    
  weather:
    visibility: 10000.0  # meters
    precipitation: 0.0  # mm/h
    temperature: 20.0  # °C

# Logging and output parameters
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  file_path: "./logs/simulation.log"
  console_output: true
  
  # Data recording
  record_data: true
  data_directory: "./data"
  data_format: "csv"  # or "json", "hdf5"
  data_compression: true
  max_file_size_mb: 100

# Debug and visualization
debug:
  enable_visualization: true
  visualization_fps: 30
  show_collision_boxes: true
  show_sensor_data: false
  show_debug_info: true

# Network parameters (if applicable)
network:
  enabled: false
  host: "localhost"
  port: 5000
  protocol: "tcp"  # or "udp"
  max_clients: 5
  
# Performance settings
performance:
  max_threads: 4
  use_gpu: false
  cache_size: 1000
  enable_profiling: false
